version: '{build}'

environment:
  WINFLEXBISON_ARCHIVE: winflexbison-2.5.16.zip
  matrix:
    - CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

matrix:
  fast_finish: true

install:
  - appveyor DownloadFile "https://downloads.sourceforge.net/project/winflexbison/%WINFLEXBISON_ARCHIVE%"
  - 7z x -y -owinflexbison\ "%WINFLEXBISON_ARCHIVE%" > nul
  - set Path=%CD%\winflexbison;%Path%
  - set Path=C:\Python36;%Path%

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DCMAKE_CXX_FLAGS_RELEASE="/Od -DNDEBUG" -G"%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="install" -DRETDEC_TESTS=ON -DRETDEC_DEV_TOOLS=ON ..

build_script:
  - cmd: cmake --build . --config Release --target install -- -m

test_script:
  # Check that the installation directory is movable and that it does not need
  # the build directory.
  - cmd: mv install ../retdec-install
  - cmd: cd ..
  # Run unit tests.
  - cmd: C:\Python36\python.exe retdec-install\bin\retdec-tests-runner.py
  # Run the decompilation script.
  - cmd: C:\Python36\python.exe retdec-install\bin\retdec-decompiler.py --help
  # Run a simple decompilation.
  - cmd: C:\msys64\usr\bin\echo.exe -e "#include <stdio.h>\n#include <stdlib.h>\nint main()\n{\n  printf(\"hello world\\\n\");\n  return 0;\n}\n" > hello-orig.c
  - cmd: cat hello-orig.c
  # Make sure 32-bit GCC will be used.
  - set Path=C:\MinGW\bin;%Path%
  - cmd: gcc.exe -o hello.exe hello-orig.c
  - cmd: hello.exe
  - cmd: C:\Python36\python.exe retdec-install\bin\retdec-decompiler.py hello.exe
  - cmd: cat hello.c
  - cmd: grep "int main(int argc, char \*\* argv)" hello.c

branches:
  only:
    # Pushes and PRs to the master branch.
    - master
    # Version tags.
    - /^v?\d+\.\d+.*$/

skip_commits:
  files:
    # Exact files.
    - .travis.yml
    - CITATION
    - Dockerfile
    - Dockerfile.dev
    - LICENSE
    - LICENSE-THIRD-PARTY
    # All .gitignore files within repository.
    - '**/.gitignore'
    # All *.md files within repository.
    - '**/*.md'
    # All README files within repository.
    - '**/README'
    - '**/README.txt'
    - '**/readme'
    - '**/readme.txt'
    # All files within doc directory, recursive.
    - doc/
    # All files within scripts/type_extractor directory, recursive.
    - scripts/type_extractor/

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
